# DATASET_NAME = "Idavidrein/gpqa"
# DATASET_SUBSET = "gpqa_diamond"
# DATASET_SPLIT = "train"

DATASET_NAME = "TIGER-Lab/MMLU-Pro"
DATASET_SUBSET = None
DATASET_SPLIT = "test"

DEBATER_MODEL = "x-ai/grok-4-fast"
JUDGE_MODEL = "openai/gpt-4o-mini"
DEBATER_TEMPERATURE = 0.0
JUDGE_TEMPERATURE = 0.0

DEBATER_REASONING_EFFORT = 'low'
DEBATER_REASONING_MAX_TOKENS = None
JUDGE_REASONING_EFFORT = None
JUDGE_REASONING_MAX_TOKENS = None

NUM_QUESTIONS = 20
RANDOM_SEED = 42
NUM_CHOICES = 4

NUM_TURNS = 1

MAX_THREADS = 5000

