DEBATE_RUN_ID = "exl35wu"

# JUDGE_MODEL = "openai/gpt-4o-mini"
JUDGE_MODEL = "openai/gpt-3.5-turbo"
JUDGE_TEMPERATURE = 0.0
JUDGE_REASONING_EFFORT = None
JUDGE_REASONING_MAX_TOKENS = None
MAX_OUTPUT_TOKENS = 5000

