DATASET_NAME = "Idavidrein/gpqa"
DATASET_SUBSET = "gpqa_diamond"
DATASET_SPLIT = "train"

MODEL_NAME = "openai/gpt-4o-mini" 
TEMPERATURE = 0.0

NUM_QUESTIONS = 198
RANDOM_SEED = 42 
NUM_CHOICES = 2  

MAX_THREADS = 5000

