# DEBATER_MODEL = "x-ai/grok-4-fast"
# DEBATER_MODEL = "x-ai/grok-4-fast"
DEBATER_MODEL = "google/gemini-3-pro-preview"


DATASET_NAME = "Idavidrein/gpqa"
DATASET_SUBSET = "gpqa_diamond"
DATASET_SPLIT = "train"

# DATASET_NAME = "TIGER-Lab/MMLU-Pro"
# DATASET_SUBSET = None
# DATASET_SPLIT = "test"

DEBATER_TEMPERATURE = 0.3

MAX_OUTPUT_TOKENS = 15000
DEBATER_REASONING_EFFORT = None
DEBATER_REASONING_MAX_TOKENS = 10000

PRIVATE_SCRATCHPAD = False

PUBLIC_ARGUMENT_WORD_LIMIT = 200
PRIVATE_REASONING_WORD_LIMIT = 1000

LENIENT_PARSING_ARGUMENT = False

NUM_QUESTIONS = 1
RANDOM_SEED = 42
NUM_CHOICES = 2
NUM_TURNS = 4

MAX_THREADS = 5000

DEBATE_MODE = "sequential"

# INTERACTIVE_JUDGE = "x-ai/grok-4-fast"
# INTERACTIVE_JUDGE_TEMPERATURE = 0.3
# INTERACTIVE_JUDGE_MAX_OUTPUT_TOKENS = 500
# INTERACTIVE_JUDGE_REASONING_EFFORT = None
# INTERACTIVE_JUDGE_REASONING_MAX_TOKENS = None

INTERACTIVE_JUDGE = None
INTERACTIVE_JUDGE_TEMPERATURE = None
INTERACTIVE_JUDGE_MAX_OUTPUT_TOKENS = None
INTERACTIVE_JUDGE_REASONING_EFFORT = None
INTERACTIVE_JUDGE_REASONING_MAX_TOKENS = None

MOCK_DEBATE_RESPONSE = False
MOCK_INTERACTIVE_JUDGE_RESPONSE = False

SPECIFIC_IDXS = [183]

########################################################################################################################################################################
# # HUMAN CONFIG 
# # DEBATER_MODEL = "x-ai/grok-4-fast"
# # DEBATER_MODEL = "x-ai/grok-4"
# DEBATER_MODEL = "moonshotai/kimi-k2-thinking"

# # DATASET_NAME = "Idavidrein/gpqa"
# # DATASET_SUBSET = "gpqa_diamond"
# # DATASET_SPLIT = "train"

# DATASET_NAME = "TIGER-Lab/MMLU-Pro"
# DATASET_SUBSET = None
# DATASET_SPLIT = "test"

# DEBATER_TEMPERATURE = 0.3

# MAX_OUTPUT_TOKENS = 5000
# DEBATER_REASONING_EFFORT = None #'low'
# DEBATER_REASONING_MAX_TOKENS = 1000

# PRIVATE_SCRATCHPAD = False

# PUBLIC_ARGUMENT_WORD_LIMIT = 200
# PRIVATE_REASONING_WORD_LIMIT = 1000

# LENIENT_PARSING_ARGUMENT = False

# NUM_QUESTIONS = 1
# RANDOM_SEED = 42
# NUM_CHOICES = 2
# NUM_TURNS = 100

# MAX_THREADS = 5000

# DEBATE_MODE = "sequential"

# MOCK_DEBATE_RESPONSE = False
# MOCK_INTERACTIVE_JUDGE_RESPONSE = False