DEBATER_MODEL = "x-ai/grok-4-fast"
# DEBATER_MODEL = "google/gemini-3-pro-preview"
# DEBATER_MODEL = "openai/gpt-4o-mini"
# DEBATER_MODEL = "openai/o3"
# DEBATER_MODEL = "openai/gpt-oss-120b"

# DATASET_NAME = "Idavidrein/gpqa"
# DATASET_SUBSET = "gpqa_diamond"
# DATASET_SPLIT = "train"

DATASET_NAME = "m-a-p/SuperGPQA"
DATASET_SUBSET = None
DATASET_SPLIT = "train"
# additional filters that can be applied
DATASET_FILTERS = {  
    'field': 'Physics',
    'difficulty': 'hard'
}
                
# DATASET_NAME = "TIGER-Lab/MMLU-Pro"
# DATASET_SUBSET = None
# DATASET_SPLIT = "test"

DEBATER_TEMPERATURE = 0.5

MAX_OUTPUT_TOKENS = 15000
DEBATER_REASONING_EFFORT = None # 'high' # None # 'low'
DEBATER_REASONING_MAX_TOKENS = None
PROVIDE_INTERNAL_REASONING_TO_SELF = True # When True, the debater will have access to its own past thought processes

PRIVATE_SCRATCHPAD = False

PUBLIC_ARGUMENT_WORD_LIMIT = None
PRIVATE_REASONING_WORD_LIMIT = None

LENIENT_PARSING_ARGUMENT = False

NUM_QUESTIONS = 5
RANDOM_SEED = 42
NUM_CHOICES = 2
NUM_TURNS = 10

MAX_THREADS = 5000

DEBATE_MODE = "sequential"

# INTERACTIVE_JUDGE = "x-ai/grok-4-fast"
# INTERACTIVE_JUDGE_TEMPERATURE = 0.3
# INTERACTIVE_JUDGE_MAX_OUTPUT_TOKENS = 500
# INTERACTIVE_JUDGE_REASONING_EFFORT = None
# INTERACTIVE_JUDGE_REASONING_MAX_TOKENS = None

INTERACTIVE_JUDGE = None
INTERACTIVE_JUDGE_TEMPERATURE = None
INTERACTIVE_JUDGE_MAX_OUTPUT_TOKENS = None
INTERACTIVE_JUDGE_REASONING_EFFORT = None
INTERACTIVE_JUDGE_REASONING_MAX_TOKENS = None

MOCK_DEBATE_RESPONSE = False
MOCK_INTERACTIVE_JUDGE_RESPONSE = False

# SPECIFIC_IDXS = [32, 92, 125, 63, 136, 179, 123, 97, 9, 129]
# SPECIFIC_IDXS = [176, 76, 118, 149, 56, 139, 3, 142, 21, 182, 22, 33, 192, 105, 110, 189, 68, 45, 75, 173]
# SPECIFIC_IDXS = [125]
# SPECIFIC_IDXS = None
SPECIFIC_IDXS = [25803, 5627, 4880, 10347, 10561]


########################################################################################################################################################################
# # HUMAN CONFIG 
# # DEBATER_MODEL = "x-ai/grok-4-fast"
# # DEBATER_MODEL = "x-ai/grok-4"
# DEBATER_MODEL = "moonshotai/kimi-k2-thinking"

# # DATASET_NAME = "Idavidrein/gpqa"
# # DATASET_SUBSET = "gpqa_diamond"
# # DATASET_SPLIT = "train"

# DATASET_NAME = "TIGER-Lab/MMLU-Pro"
# DATASET_SUBSET = None
# DATASET_SPLIT = "test"

# DEBATER_TEMPERATURE = 0.3

# MAX_OUTPUT_TOKENS = 5000
# DEBATER_REASONING_EFFORT = None #'low'
# DEBATER_REASONING_MAX_TOKENS = 1000

# PRIVATE_SCRATCHPAD = False

# PUBLIC_ARGUMENT_WORD_LIMIT = 200
# PRIVATE_REASONING_WORD_LIMIT = 1000

# LENIENT_PARSING_ARGUMENT = False

# NUM_QUESTIONS = 1
# RANDOM_SEED = 42
# NUM_CHOICES = 2
# NUM_TURNS = 100

# MAX_THREADS = 5000

# DEBATE_MODE = "sequential"

# MOCK_DEBATE_RESPONSE = False
# MOCK_INTERACTIVE_JUDGE_RESPONSE = False